language: python
python:
    - 3.2
    - 3.3

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
    - pip install -r Packages
    - pip install -r Development
    - pip install git+https://github.com/tredfern/pygsty.git

script: nosetests
